"use client";
import {useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type C={id:number;customer:string;merchant:string;amount:number;reason:string;status:string;notes:string};
type A={provider:string;summary:string;evidence_strengths:string[];missing_evidence:string[];risk_signals:string[];ai_action:string;ai_confidence:number;rule_action:string;evidence_score:number;final_route:string;rationale:string};
type D={case:C;analysis:A|null};
export default function Home(){
 const [cases,setCases]=useState<C[]>([]),[detail,setDetail]=useState<D|null>(null),[selected,setSelected]=useState<number|null>(null),[q,setQ]=useState(""),[status,setStatus]=useState(""),[metrics,setMetrics]=useState<any>(null),[busy,setBusy]=useState(false);
 async function refresh(){setCases(await fetch(`${API}/api/disputes`).then(r=>r.json()));setMetrics(await fetch(`${API}/api/metrics`).then(r=>r.json()))}
 async function open(id:number){setSelected(id);setDetail(await fetch(`${API}/api/disputes/${id}`).then(r=>r.json()))}
 useEffect(()=>{refresh()},[]);
 const list=useMemo(()=>cases.filter(c=>`${c.customer} ${c.merchant} ${c.reason}`.toLowerCase().includes(q.toLowerCase())&&(!status||c.status===status)),[cases,q,status]);
 async function analyze(){if(!selected)return;setBusy(true);await fetch(`${API}/api/disputes/${selected}/analyze`,{method:"POST"});await refresh();await open(selected);setBusy(false)}
 async function decide(s:string){if(!selected)return;await fetch(`${API}/api/disputes/${selected}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:s})});await refresh();await open(selected)}
 return <main className="shell">
  <div className="top"><div><div className="eyebrow">Product Lab · AI Products</div><h1>Payment Dispute Management System</h1><p>AI-assisted investigation with deterministic guardrails and a human final decision. Synthetic portfolio data.</p></div><span className="badge">Human-in-the-loop</span></div>
  <div className="grid4"><div className="card"><div className="small">Open cases</div><div className="metric">{metrics?.open_cases??"—"}</div></div><div className="card"><div className="small">Open exposure</div><div className="metric">${metrics?.open_exposure?.toLocaleString()??"—"}</div></div><div className="card"><div className="small">Human review</div><div className="metric">{metrics?.human_review??"—"}</div></div><div className="card"><div className="small">Analyses run</div><div className="metric">{metrics?.analyses_run??"—"}</div></div></div>
  <div className="layout"><section className="card"><h2>Dispute queue</h2><div className="toolbar"><input placeholder="Search cases…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option>OPEN</option><option>REVIEW</option><option>CONTESTED</option><option>ACCEPTED</option><option>ESCALATED</option></select></div>
   {list.map(c=><div className={`case ${selected===c.id?"active":""}`} key={c.id} onClick={()=>open(c.id)}><div className="row"><strong>#{c.id} {c.customer}</strong><span className="badge">{c.status}</span></div><div className="row small"><span>{c.merchant} · {c.reason}</span><strong>${c.amount.toFixed(2)}</strong></div></div>)}
  </section><section className="card">{!detail?<div className="empty">Select a dispute to open the analyst workspace.</div>:<>
   <div className="row"><div><div className="small">Case #{detail.case.id}</div><h2>{detail.case.customer} · {detail.case.merchant}</h2></div><span className="badge">{detail.case.status}</span></div><div className="cols"><div><div className="small">Amount</div><strong>${detail.case.amount.toFixed(2)}</strong></div><div><div className="small">Reason</div><strong>{detail.case.reason}</strong></div></div><p>{detail.case.notes}</p>
   <div className="section"><div className="row"><h2>AI case analyst</h2><button className="btn" onClick={analyze} disabled={busy}>{busy?"Analyzing…":detail.analysis?"Re-run analysis":"Analyze case"}</button></div>
   {!detail.analysis?<p>Analyze the case to surface evidence gaps and a guardrailed recommendation.</p>:<><p><strong>{detail.analysis.summary}</strong></p><div className="cols"><div><div className="small">AI proposal</div><div className="metric">{detail.analysis.ai_action}</div><div className="small">{Math.round(detail.analysis.ai_confidence*100)}% confidence · {detail.analysis.provider}</div></div><div><div className="small">Final route</div><div className="metric">{detail.analysis.final_route}</div><div className="small">Evidence {detail.analysis.evidence_score}/100 · Rules: {detail.analysis.rule_action}</div></div></div><div className="cols section"><div><strong>Evidence strengths</strong><ul>{detail.analysis.evidence_strengths.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><strong>Missing evidence</strong><ul>{detail.analysis.missing_evidence.map((x,i)=><li key={i}>{x}</li>)}</ul></div></div>{detail.analysis.risk_signals.length>0&&<div className="section"><strong>Risk signals</strong><ul>{detail.analysis.risk_signals.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}<div className="section"><strong>Why</strong><p>{detail.analysis.rationale}</p></div></>}</div>
   <div className="section"><h2>Analyst decision</h2><div className="actions"><button className="btn secondary" onClick={()=>decide("CONTESTED")}>Contest</button><button className="btn secondary" onClick={()=>decide("ACCEPTED")}>Accept</button><button className="btn secondary" onClick={()=>decide("ESCALATED")}>Escalate</button></div><p className="small">The analyst—not the AI—makes the final decision.</p></div>
  </>}</section></div>
 </main>
}
